export const APP_DRAWER = {
    TOGGLE: 'APP_DRAWER_TOGGLE'
  };
  
  export const PLPAA_REVIEW_DRAWER = {
    TOGGLE: 'PLPAA_REVIEW_DRAWER_TOGGLE'
  };
  
  export const PCG_REVIEW_CARD = {
    TOGGLE: 'PCG_REVIEW_CARD_TOGGLE'
  };
  
  export const SUPERVISOR_REVIEW_CARD = {
    TOGGLE: 'SUPERVISOR_REVIEW_CARD_TOGGLE'
  };
  
  export const FINALIZED_REVIEW_CARD = {
    TOGGLE: 'FINALIZED_REVIEW_CARD_TOGGLE'
  };
  
  export const PLPAA_REVIEW_APPROVAL_CARD = {
    TOGGLE: 'PLPAA_REVIEW_APPROVAL_CARD_TOGGLE'
  };
  